app = "rome-signal-jhffm"
primary_region = "iad"

[build]

[env]
  TZ = "America/New_York"
  SIGNAL_CLI_PATH = "signal-cli"
  SIGNAL_CONFIG_DIR = "/data/signal-cli"
  SIGNAL_ACCOUNT_NUMBER = "+15636390350"
  TARGET_SIGNAL_NUMBERS = "+16168210300,+18477085529"
  SEND_INITIAL_PROMPT = "false"
  ENABLE_SCHEDULER = "true"
  PORT = "5000"

[mounts]
  source = "signal_data"
  destination = "/data"

[[restart]]
  policy = "always"

[[vm]]
  size = "shared-cpu-1x"
  memory = "1gb"
