# publish.py
# Assembles the finished book: rebuilds every source docx, then renders an
# ordered set of PDFs into the repo root so the GitHub file listing reads as
# the table of contents. Numeric prefixes force reading order.
import os, sys, subprocess
sys.path.insert(0, os.path.dirname(__file__))
import render_check

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
os.chdir(ROOT)

# (source docx, root pdf name in reading order)
BOOK = [
    ("frontmatter/foreword.docx",                      "01_Foreword_and_the_Guardians.pdf"),
    ("frontmatter/lore_primer.docx",                   "02_The_World_of_Elaria.pdf"),
    ("sessions/session_01_gathering_of_friends.docx",  "03_Session_1_The_Gathering_of_Friends.pdf"),
    ("sessions/session_02_oakshade_village.docx",      "04_Session_2_The_Road_to_Ravenstone.pdf"),
    ("sessions/session_03_quest_for_knowledge.docx",   "05_Session_3_The_Quest_for_Knowledge.pdf"),
    ("sessions/session_04_shadows_and_songs.docx",     "06_Session_4_Awakening_to_Shadows_and_Songs.pdf"),
    ("sessions/session_05_curse_of_davy_jones.docx",   "07_Session_5_The_Curse_of_Davy_Jones.pdf"),
    ("sessions/session_06_wraithpine.docx",            "08_Session_6_Lanterns_in_the_Fog.pdf"),
    ("sessions/session_07_gearhaven.docx",             "09_Session_7_Gearhaven_the_Clockwork_City.pdf"),
    ("sessions/session_08_underroot.docx",             "11_Session_8_Underroot.pdf"),
    ("compendium/the_compendium.docx",                 "12_The_Compendium.pdf"),
]

# Source builders to run first (session 7 has no builder; it is edited in place).
BUILDERS = [
    "build_foreword.py", "build_lore.py",
    "build_session_01.py", "build_session_02.py", "build_session_03.py",
    "build_session_04.py", "build_session_05.py", "build_session_06.py",
    "build_session_08.py",
    "build_compendium.py", "build_bestiary.py", "build_compendium_full.py",
]

def rebuild_sources():
    for b in BUILDERS:
        r = subprocess.run([sys.executable, os.path.join("templates", b)],
                           capture_output=True, text=True)
        tag = "ok" if r.returncode == 0 else "FAIL"
        print(f"  [{tag}] {b}", r.stderr.strip()[:200] if r.returncode else "")

def render_book():
    for src, pdf in BOOK:
        if not os.path.exists(src):
            print(f"  MISSING {src}"); continue
        render_check.docx_to_pdf(src, os.path.join(ROOT, pdf))
        print(f"  {pdf}")


# The heroes' real character sheets are the ReportLab PDFs (full table-ready
# layout), merged into the Compendium right after the Part IV divider page.
# Each PDF starts its own page, so every hero begins after a fresh page break.
# NOTE: these PDFs are regenerated by hand from characters/builders/ (run the
# per-hero builder from that folder). All three builders are content-synced to
# the current sheets (since 8d53200). Publish still does NOT regenerate them
# here: sheet rebuilds are deliberate, reviewed events, not a book-render side
# effect.
CHAR_SHEETS = [
    "characters/lilly_glimmergear_sheet_v3.pdf",
    "characters/stabby_sharpblade_sheet_v3.pdf",
    "characters/ursa_catchum_sheet_v3.pdf",
]


def merge_char_sheets():
    from pypdf import PdfWriter
    comp = os.path.join(ROOT, "10_The_Compendium.pdf")
    if not os.path.exists(comp):
        print("  skip char-sheet merge: compendium PDF missing"); return
    w = PdfWriter(); w.append(comp)
    for rel in CHAR_SHEETS:
        p = os.path.join(ROOT, rel)
        if os.path.exists(p):
            w.append(p); print(f"  + {os.path.basename(p)}")
        else:
            print(f"  MISSING char sheet {rel}")
    with open(comp, "wb") as f:
        w.write(f)
    print("  char sheets merged into 10_The_Compendium.pdf")

if __name__ == "__main__":
    if "--pdf-only" not in sys.argv:
        print("rebuilding sources...")
        rebuild_sources()
    print("rendering book PDFs to repo root...")
    render_book()
    print("merging character sheets into the Compendium...")
    merge_char_sheets()
    print("done")
